{% set version = "1.9.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-regsem
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/regsem_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/regsem/regsem_{{ version }}.tar.gz
  sha256: 7392bd644efe82f96da0df470a962de398f1d0162273cba1ff31c2ecd7f17a53

build:
  merge_build_host: true  # [win]
  number: 1

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-rsolnp
    - r-lavaan
    - libblas
    - libcblas
    - liblapack

  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-rcpparmadillo
    - r-rsolnp
    - r-lavaan

test:
  commands:
    - $R -e "library('regsem')"           # [not win]
    - "\"%R%\" -e \"library('regsem')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=regsem
  license: GPL-2.0-or-later
  summary: Uses both ridge and lasso penalties (and extensions) to penalize specific parameters in structural equation models. The package offers additional cost functions, cross validation, and other extensions beyond traditional structural equation models. Also contains a function to perform exploratory mediation (XMed).

  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
